# .streamlit/secrets.toml

# Shared authentication settings
[auth]
redirect_uri = "https://recruitfrontend-911008082076.asia-south1.run.app/oauth2callback" # **MUST match your IdP configuration**
cookie_secret = "f15dbb98c5e46e2b08fd298fa16d207922799c274fdf6116a6923548f1bd8fab" # Generate a strong, random string here

# Google Identity Provider configuration
[auth.google]
client_id = "911008082076-3gbodlshiannne2ufr5fgp7kt1d1uvnc.apps.googleusercontent.com"
client_secret="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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
